package main

//json解析器的七种类型
const (
	EASY_NULL = iota
	EASY_FALSE
	EASY_TRUE
	EASY_NUMBER
	EASY_STRING
	EASY_ARRAY
	EASY_OBJECT
)

//json树的节点
type EasyValue struct {
	vType int
	num   float64
	str   []byte
	len   int
	e     []EasyValue
	o     []EasyObj
}

type EasyObj struct {
	key   string
	value EasyValue
}

//解析后的返回值
const (
	EASY_PARSE_OK = iota
	EASY_PARSE_EXPECT_VALUE
	EASY_PARSE_INVALID_VALUE
	EASY_PARSE_ROOT_NOT_SINGULAR
	EASY_PARSE_NUMBER_TOO_BIG
	EASY_PARSE_MISS_QUOTATION_MARK
	EASY_PARSE_INVALID_STRING_ESCAPE
	EASY_PARSE_INVALID_STRING_CHAR
	EASY_PARSE_INVALID_UNICODE_HEX
	EASY_PARSE_INVALID_UNICODE_SURROGATE
	EASY_PARSE_MISS_COMMA_OR_SQUARE_BRACKET
	EASY_PARSE_MISS_KEY
	EASY_PARSE_MISS_COLON
	EASY_PARSE_MISS_COMMA_OR_CURLY_BRACKET
)
